version: '3.7'
services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
      - /efs/website:/var/www/html
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: AWS RDS Endpoint
      WORDPRESS_DB_USER: user BD RDS
      WORDPRESS_DB_PASSWORD: password BD RDS
      WORDPRESS_DB_NAME: name BD RDS
      WORDPRESS_TABLE_CONFIG: wp_
